### ISSUE TITLE
Documentation endpoint or new endpoint to return Mission Pages

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/pds-api-server#25]
Resource or mission pages include some useful documentation for each of the individual missions, e.g. go to https://pds.nasa.gov/datasearch/data-search/ and search for Cassini, we should direct people to https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/Cassini/Cassini.html .

This can be found where `resource_type:Information.Investigation`, e.g.:

https://pds.nasa.gov/services/search/select?wt=json&q=resource_type:Information.Investigation%20AND%20investigation_name:%22MARS%20SCIENCE%20LABORATORY%22

**Comment by tdddblog** [comment]
We already have "ctx_invest" (context investigation) collection which has the same information except "resource_url" field. I'll add "resource_url" data to existing collection, so it can be queried by existing context APIs.
